-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.14.0.75.2
-- Module  Version: 2.8
--C:\tools\diamond_3.14\ispfpga\bin\nt64\scuba.exe -w -n rom_7seg4 -lang vhdl -synth synplify -bus_exp 7 -bb -arch xo2c00 -type rom -addr_width 4 -num_rows 16 -data_width 7 -outdata REGISTERED -memfile c:/users/yasuno/documents/dev/7seg4/pld-rom/romdata.mem -memformat bin 

-- Fri Jan 10 03:33:17 2025

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library MACHXO2;
use MACHXO2.components.all;
-- synopsys translate_on

entity rom_7seg4 is
    port (
        Address: in  std_logic_vector(3 downto 0); 
        OutClock: in  std_logic; 
        OutClockEn: in  std_logic; 
        Reset: in  std_logic; 
        Q: out  std_logic_vector(6 downto 0));
end rom_7seg4;

architecture Structure of rom_7seg4 is

    -- internal signal declarations
    signal qdataout6_ffin: std_logic;
    signal qdataout5_ffin: std_logic;
    signal qdataout4_ffin: std_logic;
    signal qdataout3_ffin: std_logic;
    signal qdataout2_ffin: std_logic;
    signal qdataout1_ffin: std_logic;
    signal qdataout0_ffin: std_logic;

    -- local component declarations
    component FD1P3DX
        port (D: in  std_logic; SP: in  std_logic; CK: in  std_logic; 
            CD: in  std_logic; Q: out  std_logic);
    end component;
    component ROM16X1A
        generic (INITVAL : in std_logic_vector(15 downto 0));
        port (AD3: in  std_logic; AD2: in  std_logic; AD1: in  std_logic; 
            AD0: in  std_logic; DO0: out  std_logic);
    end component;
    attribute GSR : string; 
    attribute GSR of FF_6 : label is "ENABLED";
    attribute GSR of FF_5 : label is "ENABLED";
    attribute GSR of FF_4 : label is "ENABLED";
    attribute GSR of FF_3 : label is "ENABLED";
    attribute GSR of FF_2 : label is "ENABLED";
    attribute GSR of FF_1 : label is "ENABLED";
    attribute GSR of FF_0 : label is "ENABLED";
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    FF_6: FD1P3DX
        port map (D=>qdataout6_ffin, SP=>OutClockEn, CK=>OutClock, 
            CD=>Reset, Q=>Q(6));

    FF_5: FD1P3DX
        port map (D=>qdataout5_ffin, SP=>OutClockEn, CK=>OutClock, 
            CD=>Reset, Q=>Q(5));

    FF_4: FD1P3DX
        port map (D=>qdataout4_ffin, SP=>OutClockEn, CK=>OutClock, 
            CD=>Reset, Q=>Q(4));

    FF_3: FD1P3DX
        port map (D=>qdataout3_ffin, SP=>OutClockEn, CK=>OutClock, 
            CD=>Reset, Q=>Q(3));

    FF_2: FD1P3DX
        port map (D=>qdataout2_ffin, SP=>OutClockEn, CK=>OutClock, 
            CD=>Reset, Q=>Q(2));

    FF_1: FD1P3DX
        port map (D=>qdataout1_ffin, SP=>OutClockEn, CK=>OutClock, 
            CD=>Reset, Q=>Q(1));

    FF_0: FD1P3DX
        port map (D=>qdataout0_ffin, SP=>OutClockEn, CK=>OutClock, 
            CD=>Reset, Q=>Q(0));

    mem_0_6: ROM16X1A
        generic map (initval=> X"D7ED")
        port map (AD3=>Address(3), AD2=>Address(2), AD1=>Address(1), 
            AD0=>Address(0), DO0=>qdataout6_ffin);

    mem_0_5: ROM16X1A
        generic map (initval=> X"279F")
        port map (AD3=>Address(3), AD2=>Address(2), AD1=>Address(1), 
            AD0=>Address(0), DO0=>qdataout5_ffin);

    mem_0_4: ROM16X1A
        generic map (initval=> X"2FFB")
        port map (AD3=>Address(3), AD2=>Address(2), AD1=>Address(1), 
            AD0=>Address(0), DO0=>qdataout4_ffin);

    mem_0_3: ROM16X1A
        generic map (initval=> X"7B6D")
        port map (AD3=>Address(3), AD2=>Address(2), AD1=>Address(1), 
            AD0=>Address(0), DO0=>qdataout3_ffin);

    mem_0_2: ROM16X1A
        generic map (initval=> X"FD45")
        port map (AD3=>Address(3), AD2=>Address(2), AD1=>Address(1), 
            AD0=>Address(0), DO0=>qdataout2_ffin);

    mem_0_1: ROM16X1A
        generic map (initval=> X"DFF1")
        port map (AD3=>Address(3), AD2=>Address(2), AD1=>Address(1), 
            AD0=>Address(0), DO0=>qdataout1_ffin);

    mem_0_0: ROM16X1A
        generic map (initval=> X"EF7C")
        port map (AD3=>Address(3), AD2=>Address(2), AD1=>Address(1), 
            AD0=>Address(0), DO0=>qdataout0_ffin);

end Structure;

-- synopsys translate_off
library MACHXO2;
configuration Structure_CON of rom_7seg4 is
    for Structure
        for all:FD1P3DX use entity MACHXO2.FD1P3DX(V); end for;
        for all:ROM16X1A use entity MACHXO2.ROM16X1A(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
